---
# Source: url-shortener-helm/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: url-shortener
  labels:
    helm.sh/chart: url-shortener-helm-0.1.0
    app.kubernetes.io/name: url-shortener-helm
    app.kubernetes.io/instance: url-shortener
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: url-shortener-helm/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secret
  labels:
    helm.sh/chart: url-shortener-helm-0.1.0
    app.kubernetes.io/name: url-shortener-helm
    app.kubernetes.io/instance: url-shortener
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  AUTH_PASSWORD: ZGV2cGFzcw==
  AUTH_USER: ZGV2dXNlcg==
---
# Source: url-shortener-helm/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
  labels:
    helm.sh/chart: url-shortener-helm-0.1.0
    app.kubernetes.io/name: url-shortener-helm
    app.kubernetes.io/instance: url-shortener
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  DB_FILE: "/app/urls-dev.db"
  ENVIRONMENT: "dev"
---
# Source: url-shortener-helm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: url-shortener
  labels:
    helm.sh/chart: url-shortener-helm-0.1.0
    app.kubernetes.io/name: url-shortener-helm
    app.kubernetes.io/instance: url-shortener
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: url-shortener-helm
    app.kubernetes.io/instance: url-shortener
---
# Source: url-shortener-helm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  labels:
    helm.sh/chart: url-shortener-helm-0.1.0
    app.kubernetes.io/name: url-shortener-helm
    app.kubernetes.io/instance: url-shortener
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: url-shortener-helm
      app.kubernetes.io/instance: url-shortener
  template:
    metadata:
      labels:
        helm.sh/chart: url-shortener-helm-0.1.0
        app.kubernetes.io/name: url-shortener-helm
        app.kubernetes.io/instance: url-shortener
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      imagePullSecrets:
        - name: regcred
      serviceAccountName: url-shortener
      securityContext:
        fsGroup: 2000
      containers:
        - name: url-shortener-helm
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsGroup: 3000
            runAsNonRoot: true
            runAsUser: 1000
          image: "devd/babbel-task:latest"
          imagePullPolicy: Always
          command: ["/app/url-shortener"]
          workingDir: /app
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: url-shortener-config
            - secretRef:
                name: url-shortener-secret
          livenessProbe:
            httpGet:
              path: /login
              port: http
          readinessProbe:
            httpGet:
              path: /login
              port: http
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /app/data
              name: sqlite-storage
              readOnly: false
      volumes:
        - emptyDir: {}
          name: sqlite-storage
