# values-dev.yaml
image:
  repository: devd/babbel-task
  tag: dev-latest  # will be replaced by GitHub Actions
  pullPolicy: IfNotPresent

env:
  ENVIRONMENT: dev
  DB_FILE: "/app/urls-dev.db"
  AUTH_USER: "devuser"
  AUTH_PASSWORD: "devpass"

