{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "url-shortener-helm.fullname" . }}-external-secret
  labels:
    {{- include "url-shortener-helm.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ include "url-shortener-helm.fullname" . }}-secret
    creationPolicy: Owner
  data:
    - secretKey: AUTH_USER
      remoteRef:
        key: {{ .Values.externalSecrets.authUserKey }}
    - secretKey: AUTH_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.authPasswordKey }}
    {{- if .Values.externalSecrets.dbUrl }}
    - secretKey: DB_URL
      remoteRef:
        key: {{ .Values.externalSecrets.dbUrl }}
    {{- end }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStoreName }}
  labels:
    {{- include "url-shortener-helm.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.externalSecrets.awsRegion }}
      auth:
        secretRef:
          accessKeyId:
            name: aws-secret
            key: access-key-id
          secretAccessKey:
            name: aws-secret
            key: secret-access-key
{{- end }}