{{- if .Values.envSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "url-shortener-helm.fullname" . }}-secret
  labels:
    {{- include "url-shortener-helm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.env }}
  {{- if or (eq $key "AUTH_USER") (eq $key "AUTH_PASSWORD") }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}