{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount # This will changed for prod as this will requires IRSA AWS for https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html for roles which can be used by serviceaccount to access resources which application needs for running like RDS, S3 , SSM, Parameter store. AWS IAM policy are also required to have perms for accessing the specfic resoures which can be done via Terraform 
metadata:
  name: {{ include "url-shortener-helm.serviceAccountName" . }}
  labels:
    {{- include "url-shortener-helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
